module General where

import Display
import Markdown
import Html (..)
import Html.Attributes as Attr

content : Html
content =  Markdown.toHtml """
# Some Gibberish

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam lacinia rhoncus risus, nec hendrerit velit imperdiet a. Proin cursus augue mauris, quis egestas risus finibus at. Nam sit amet rhoncus erat, ut bibendum massa. Suspendisse metus ante, tincidunt ut lobortis vel, varius suscipit mauris. Sed pellentesque aliquam massa, at tincidunt turpis fringilla sit amet. Vestibulum id interdum dolor. Donec ac ipsum dignissim, auctor urna ut, aliquam nunc.

Donec interdum tortor erat, a sodales lectus tincidunt et. Vivamus ante nisi, laoreet ac nibh quis, dapibus congue nunc. Sed faucibus et lectus vitae pulvinar. Phasellus efficitur cursus erat, et ultrices ante ullamcorper non. Donec non mauris quis nunc iaculis tempor. Donec a enim non ante gravida elementum. Pellentesque convallis arcu id tincidunt gravida.

Mauris et malesuada magna. Sed eu lacinia ipsum. Sed porttitor fermentum lorem, in convallis lectus sodales ut. Sed tempor lobortis sodales. Integer sagittis a ex facilisis consectetur. Sed semper, metus sit amet semper elementum, sapien ligula sagittis magna, a viverra tellus ante a ligula. Curabitur pharetra congue elit, vel commodo metus. Donec a purus id lectus placerat aliquet. Nam non risus vel orci egestas luctus. Nam vel convallis quam, in lacinia metus. Morbi feugiat aliquam justo eu vestibulum.

Nam dapibus bibendum tincidunt. Nullam nec orci vel lectus tempus commodo nec quis ante. Vestibulum ligula mi, pretium eget eros eget, hendrerit rhoncus dolor. Sed a eleifend dui. Quisque venenatis semper laoreet. Vivamus sit amet lobortis nisl. Donec tincidunt eros fermentum arcu imperdiet eleifend. Sed pretium tempor justo ut molestie. Quisque quam dolor, tincidunt nec nulla nec, vehicula maximus ex.

Nulla rhoncus nibh ut magna fringilla, vitae pharetra augue tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent nec felis vitae nibh lobortis tincidunt eu et felis. Nulla efficitur elementum tristique. Suspendisse suscipit dui eros, non maximus lorem efficitur at. Phasellus eget arcu at turpis placerat imperdiet. Sed tristique, est eu ornare scelerisque, elit ex rhoncus mi, ac consequat ligula lorem et augue.

Proin ac facilisis tellus, eu volutpat sapien. Suspendisse id tellus et magna mollis euismod. Aenean vitae leo vitae sem egestas tincidunt quis ac leo. Maecenas gravida velit a nunc bibendum, ac facilisis libero fringilla. Duis et nulla sit amet justo aliquam ultricies. Phasellus feugiat magna vel porta condimentum. Cras ac eleifend augue, a ullamcorper magna. Vestibulum tellus est, tempus ac bibendum quis, rutrum sed nisl. Phasellus mattis ligula nec tellus ultrices, vitae dictum arcu ultrices.

Quisque tristique mi nec nisi luctus, at dapibus felis varius. Sed diam velit, aliquam in convallis at, posuere sed orci. Maecenas lacinia finibus dui ut feugiat. Vivamus convallis ipsum sit amet velit tristique porta. Donec at lacinia dui. Aliquam gravida nisl ut volutpat iaculis. Nam eget enim ultricies odio sodales fermentum in nec quam. Nunc metus dui, ornare sit amet dapibus ut, accumsan et sapien. Fusce congue erat id ultricies convallis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi rhoncus dolor a quam tincidunt maximus. Morbi ac metus purus.

# Gibberish++

Morbi ac dui neque. Proin volutpat est turpis, ut sagittis urna fermentum sit amet. Curabitur molestie malesuada tortor, et ultricies sem posuere eget. Curabitur id est eu nunc ultricies porttitor. Morbi consequat odio quis pellentesque blandit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse metus nunc, efficitur vel magna sed, tincidunt euismod lorem. Pellentesque nec elit at mi fermentum blandit. Donec mattis tincidunt mi, quis dignissim risus convallis commodo. Praesent sit amet tristique leo. Pellentesque sed dolor tellus. Sed vel pharetra lacus. Mauris ac ligula leo. Morbi sed euismod nisl, vitae condimentum lorem. Sed et risus auctor, faucibus metus quis, commodo elit. Donec iaculis nisl eu feugiat pharetra.

Duis accumsan magna sed lorem blandit, vel luctus massa scelerisque. Praesent at lorem lacus. Sed sodales nibh eget turpis volutpat facilisis. Sed at elit urna. Cras porttitor egestas est eu scelerisque. Aliquam non diam nec metus scelerisque interdum nec nec massa. Etiam mi sem, semper sed mi sed, egestas imperdiet dolor. Nullam id sodales dolor, in viverra nulla. Suspendisse iaculis lacus vel tortor ullamcorper egestas.

Phasellus vestibulum sapien et ligula posuere varius. Suspendisse at dolor semper, mollis arcu vel, aliquet nisl. Fusce rhoncus volutpat efficitur. Morbi dignissim consequat nibh sed sodales. Aliquam turpis ligula, mattis vitae dolor id, pellentesque auctor risus. Nulla rutrum massa ut diam placerat condimentum ut in magna. Sed convallis metus nisi, non gravida ex blandit efficitur. Nam sed auctor lacus. Mauris ultrices, nisi sit amet consectetur varius, nunc velit consectetur nibh, vel blandit lorem tellus sed quam. Morbi at elit quis augue placerat imperdiet eget quis purus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis a tempor metus. Ut tempus pharetra magna in accumsan. Maecenas sagittis sit amet dolor eu aliquet. Nullam et viverra risus. Curabitur maximus sagittis nibh, sed dapibus nunc accumsan at. Vivamus finibus dolor in dolor molestie aliquam. Aliquam erat volutpat. Nunc arcu sapien, vehicula sit amet mi iaculis, maximus auctor dolor. Nam sollicitudin aliquet est, lacinia viverra enim porta id. Duis in tempor nibh.

Donec placerat elementum lacus, vel vulputate justo commodo vitae. Nulla nec pretium urna. Aenean venenatis ligula a ante laoreet, eu semper magna viverra. Fusce laoreet porttitor dui at consectetur. Curabitur elit ex, viverra at posuere vitae, pulvinar id purus. Suspendisse sed faucibus tortor. Proin arcu odio, interdum non est a, viverra sodales sem. Pellentesque tempus purus in elit feugiat rhoncus. In erat massa, vestibulum quis diam id, faucibus imperdiet erat. Sed et vehicula mi. Ut elementum felis ut lacus fringilla aliquet. Integer sit amet tempor arcu, et pulvinar mi. Nunc et nisl magna.

Morbi convallis nulla at fringilla volutpat. Donec vitae tincidunt orci. Aliquam elit dolor, porttitor ut interdum eget, porttitor non ipsum. Sed at est vel erat facilisis pharetra. Sed nec libero et risus aliquam facilisis. Duis quis tortor arcu. Mauris nec dui sit amet leo malesuada tincidunt. Aliquam faucibus, nulla sed vehicula finibus, mauris magna commodo mauris, quis consectetur erat tortor nec ante. Aenean scelerisque lacus quis tellus dapibus pulvinar. Integer ac dictum nisi.

Etiam maximus orci ac felis pretium commodo. Quisque eget placerat erat, id auctor orci. Proin vel diam condimentum, vulputate tortor et, viverra erat. Maecenas pretium nibh eu tortor semper dignissim. Nullam molestie eros ac mollis lacinia. Phasellus id condimentum enim. Phasellus sit amet nulla nec urna iaculis viverra.

### More Gibberish

Sed gravida, quam quis laoreet eleifend, neque magna auctor turpis, eget facilisis enim libero dapibus leo. Ut sollicitudin, urna at aliquet posuere, nisl purus elementum risus, vitae laoreet tellus nunc sit amet enim. Vivamus luctus ornare lorem. Donec ac quam consequat enim tempor commodo sit amet id tellus. Proin laoreet feugiat quam nec rutrum. In sed tempus diam, nec vehicula nisi. Phasellus feugiat risus ut arcu imperdiet cursus. In volutpat, nisl sit amet elementum volutpat, diam lectus dictum odio, ut vehicula justo ante ultrices nulla. Morbi vel dolor et augue efficitur viverra. Mauris ut aliquet lorem, ut congue felis. Cras ultricies nibh sit amet urna pulvinar, id lacinia arcu porta. Suspendisse vel lobortis nibh.

Praesent quis nisi justo. Nam porta eu risus vitae pharetra. Sed imperdiet volutpat semper. Suspendisse sit amet condimentum nibh. Mauris id bibendum sapien. Integer quis nibh in dolor accumsan malesuada. Quisque venenatis molestie ullamcorper. Maecenas elementum libero quis massa tristique varius. Phasellus quis suscipit tellus. Nullam convallis lectus quis massa tincidunt ullamcorper. Curabitur odio nunc, blandit sit amet ultrices vel, sollicitudin id sem. Vestibulum venenatis sem non egestas vulputate. Sed ipsum tellus, accumsan vel nulla eu, euismod sagittis eros.

Quisque ac nulla arcu. Integer urna diam, fermentum nec eleifend ut, ullamcorper quis dolor. Proin viverra elit eu bibendum congue. Sed vestibulum tincidunt turpis ut imperdiet. Cras at tellus at tortor posuere elementum nec in orci. Aenean et felis ante. Donec iaculis euismod porta. Etiam nec mauris id nisi venenatis venenatis. Praesent lacinia commodo massa, a pretium libero dictum ac.

Nam aliquet efficitur purus ac lobortis. Vivamus orci tortor, dignissim ut quam non, vulputate aliquet justo. Quisque vehicula gravida metus vel venenatis. Sed vulputate lacus non augue tincidunt gravida. Proin aliquam eros turpis, sed facilisis quam posuere eu. In cursus pellentesque ipsum, a volutpat mauris dictum non. Nullam viverra metus lacus, vel elementum est sollicitudin sit amet. Nullam fermentum nunc orci, quis eleifend libero vulputate non. Donec sed magna sapien. Aenean sit amet dui sagittis metus pellentesque dapibus a in odio. Nulla eu consectetur lorem. Nam suscipit, lectus a ullamcorper vehicula, enim mauris hendrerit ex, mollis malesuada ex eros fermentum mi.

Aenean vel eleifend nibh, in pretium purus. Suspendisse ligula eros, congue a sagittis ac, iaculis in justo. Nam ut dapibus risus, a congue sapien. Aenean tempus venenatis mauris vel sodales. Donec eu semper enim. Etiam cursus porta quam, in dapibus orci rutrum ullamcorper. Phasellus a efficitur lorem. Vestibulum tempor mauris nec volutpat tristique. Integer elementum sed erat maximus semper. Praesent feugiat nisi eu metus eleifend, et eleifend eros aliquet.

Quisque accumsan sed est et blandit. Etiam bibendum, sapien a mattis commodo, arcu magna faucibus dui, id ultrices nisl ex at lorem. Duis faucibus iaculis auctor. Nulla pretium lorem rutrum libero bibendum iaculis. Maecenas imperdiet, ex eget ultricies fringilla, leo enim rutrum lorem, eu vestibulum urna urna sit amet orci. Cras sit amet tincidunt leo, vel ornare lorem. Cras ipsum eros, lobortis ac odio vel, vulputate tempus tortor. Suspendisse ut tempor justo, nec tempus tortor. Donec vitae massa lacus. Etiam viverra vitae ligula vel pharetra. Duis vel libero vitae tellus porta tincidunt. Aliquam pretium mollis mi, in fermentum libero. Sed nunc velit, aliquam at diam at, elementum efficitur justo.

Donec imperdiet, eros sit amet ornare hendrerit, nibh ipsum laoreet ipsum, ut tempus elit est eget ligula. Ut fermentum tempor enim nec pretium. Phasellus eu diam sit amet augue fringilla bibendum ac ut velit. Integer sagittis nisi mattis diam accumsan sollicitudin. Duis id mi dapibus, tincidunt risus id, ultrices dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean feugiat nunc orci, vel scelerisque dolor lobortis in. Nam sem dolor, sagittis ut ullamcorper vitae, imperdiet ac ex. Suspendisse a quam nisi. Suspendisse nec arcu sapien.

Sed ligula tortor, eleifend vel vestibulum vel, pellentesque quis est. Pellentesque vestibulum lacus mauris. Cras sagittis tortor vel dolor congue, sed accumsan lectus semper. Ut a leo vitae libero bibendum rutrum cursus a turpis. Vestibulum eleifend, felis interdum eleifend congue, ex ex pellentesque orci, ac condimentum ligula lacus quis eros. Donec lorem enim, imperdiet et lacinia quis, consectetur et risus. Pellentesque tempor mauris non magna blandit, a bibendum turpis dictum. Mauris bibendum, ante eu dapibus feugiat, diam ante porta enim, eu molestie neque augue non ipsum. Fusce aliquam feugiat molestie. Fusce ornare elit id enim hendrerit, ac dictum nibh faucibus. Nunc hendrerit nec tellus non maximus. Vestibulum condimentum arcu a felis blandit dapibus. Aliquam vitae lacinia leo, sed ultrices augue. Nunc viverra pellentesque lacus aliquet aliquam.

# Conclusion Gibberish

Pellentesque sit amet ultrices ipsum. Aliquam aliquet lectus arcu, ullamcorper interdum orci sollicitudin id. Praesent at aliquam tortor, ut accumsan nulla. Curabitur sollicitudin dignissim elit, ac euismod augue condimentum et. Donec sed ullamcorper lacus, sit amet mattis nibh. Pellentesque in sem eget velit elementum vestibulum id eget sem. Quisque massa diam, egestas elementum ligula nec, accumsan volutpat dolor. Fusce gravida est ac molestie feugiat.

Morbi suscipit, diam non placerat commodo, urna elit maximus ipsum, non ornare nunc diam sed nunc. Etiam in placerat risus. Phasellus mollis placerat ornare. Vestibulum id fringilla ante. Curabitur vel quam ante. Pellentesque eget porttitor eros, at congue nisl. Nulla eget dolor facilisis, scelerisque dolor eu, ornare magna. Proin sit amet mi at ipsum rutrum faucibus. Duis viverra orci nec mollis egestas. In in consectetur lectus. Curabitur vehicula purus non felis fringilla hendrerit. Cras dictum nulla dolor. Donec non scelerisque tortor, ut condimentum risus. Proin dapibus id mauris vel venenatis.

Nullam malesuada molestie lacinia. In suscipit mauris eget ligula accumsan, vel lacinia sapien feugiat. Curabitur quis enim iaculis, pharetra tellus at, sagittis erat. Duis justo ante, mollis finibus ante a, tempus tincidunt augue. Nunc elementum nec sem tempus interdum. Ut in commodo purus. Praesent ut hendrerit risus. Aenean porttitor sagittis arcu. Etiam nulla orci, sagittis ac magna eu, congue ultrices leo. Quisque sit amet auctor purus. Vestibulum eu nisl diam. Nunc a ultrices magna.
"""
                       

main = Display.withContent content